### ISSUE TITLE
invalid device function with GTX 980

### ISSUE THREAD

**Issue by GoogleCodeExporter** [akrizhevsky/cuda-convnet2#15]
```
When i try to run training example of cuda-convnet2 i get this error :

src/nvmatrix.cu(394) : getLastCudaError() CUDA error : kSetupCurand: Kernel 
execution failed : (8) invalid device function .

I have GTX 980 on my machine and it has compute capability 5.2

I tried to modify makefiles in cudaconv3 & cudaconvnet & nvmatrix like this and 
to add 52 instead of 50 tooand i stil have same error. 

GENCODE_SM35    := -gencode arch=compute_35,code=sm_35
GENCODE_FLAGS   := $(GENCODE_SM35)

to

GENCODE_SM35    := -gencode arch=compute_35,code=sm_35
GENCODE_SM50    := -gencode arch=compute_50,code=sm_50
GENCODE_FLAGS   := $(GENCODE_SM50)

```

Original issue reported on code.google.com by `Afterma...@gmail.com` on 11 Apr 2015 at 9:21

Attachments:
- [log.txt.txt](https://storage.googleapis.com/google-code-attachments/cuda-convnet2/issue-15/comment-0/log.txt.txt)

**Comment by grandbander** [comment]
I fixed it with this.
GENCODE_SM52    := -gencode arch=compute_52,code=sm_52

**Comment by li7hui** [comment]
I have the GTX960, I met the same error, and didn't fix it.
